[package]
name = "abc059"
version = "0.1.0"
authors = ["Takahiro Kawashige <lapavoni@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "0.4.3"

[profile.release]
lto = true
panic = 'abort'
